# Generated by Django 5.1.1 on 2025-08-22 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AZexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('exam_date', models.DateTimeField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Изображение с заданием')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('participants', models.ManyToManyField(related_name='xxexam_participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники (пользователи)')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ('-created_at',),
            },
        ),
    ]
